// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.Data;

#nullable disable

namespace StudentManagement.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StudentManagement.Data.Student", b =>
                {
                    b.Property<int>("RollNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("PlacementStatus")
                        .HasColumnType("longtext");

                    b.HasKey("RollNumber");

                    b.ToTable("student");
                });

            modelBuilder.Entity("StudentManagement.Models.Placement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<int?>("CtcOffered")
                        .HasColumnType("int");

                    b.Property<string>("JobRole")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionsAsked")
                        .HasColumnType("longtext");

                    b.Property<int>("RollNumber")
                        .HasColumnType("int");

                    b.Property<string>("SelectionProcess")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("RollNumber");

                    b.ToTable("placement");
                });

            modelBuilder.Entity("StudentManagement.Models.Placement", b =>
                {
                    b.HasOne("StudentManagement.Data.Student", "Student")
                        .WithMany()
                        .HasForeignKey("RollNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
